# - docker compose file for both couchdb + the dtou app
# - run this in the project root, i.e. $> docker-compose -f docker/docker-compose.yml up --build -d
# - attach to the router logs with docker logs -f dtou-router
version: "3"
services:
  router:
# - use this if not running on host network
#    depends_on:
#      - couchdb
    container_name: dtou-router
    image: lmok/dtou-router:dev
    build:
      dockerfile: ./docker/RouterDockerfile
      context:    ..
    ports:
      - 80:80
    volumes:
      # - persist configuration data (hashname)
      - ~/.dtou:/mnt/dtou
    # - if using ctr as a telehash router on a linux instance, must set network to host
    #   this will also disable depends_on
    network_mode: "host"
    environment:
      TH_CACHE: "true"
      PDB_NAME: http://localhost:5984/items
      TH_PRECONNECT: http://52.90.1.84
  couchdb:
    container_name: couchdb
    image: lmok/dtou-couchdb:dev
    build:
      dockerfile: ./docker/CouchdbDockerfile
      context:    ..
    ports:
      - 5984:5984
    volumes:
      # - persist couchdb documents
      - ~/.dtou/couchdb/data:/usr/local/var/lib/couchdb

# - use this in previous versions to prevent volume being deleted
#volumes:
#  ~/.dtou/couchdb/data:
#    external: true
